import { apiGet, apiPost, apiPut } from '@/lib/api';
export type Source = 'staff' | 'qr_web' | 'customer_tablet';
export type Mode = 'manual' | 'immediate';
export type Area = { id: string; name: string };
export type Destination = { id: string; name: string; type: 'screen' | 'printer'; paused: boolean; address?: string; port?: number; profile?: string };
export type Targets = { areas: string[]; destinations: string[] };
export type RoutingRule = Targets & { kind: 'item' | 'category'; reference_id: number };
export type Bundle = { display?: { fallback_minutes: number }; areas: Area[]; destinations: Destination[]; rules: RoutingRule[]; all_items: string[]; fallback: Targets; policies?: Record<Source, Mode> };
export type BranchSummary = { uuid: string; name: string; name_ar: string | null; status: string; mode: string; desired_version: number; applied_version: number; activation_state: string; policies: Record<Source, Mode>; overrides: Partial<Record<Source, Mode>>; applied_policies: Record<Source, Mode> | null; pending: boolean };
export type Settings = { can_manage: boolean; can_apply_all: boolean; defaults: Record<Source, Mode>; branches: BranchSummary[] };
export type Item = { id: number; name: string; name_ar: string | null; category_id?: number | null };
export type Detail = BranchSummary & { bundle: Bundle; devices: { uuid: string; name: string | null; type: string; enrolled: boolean; coordinator: boolean }[]; activation_available: boolean; delivery_counts: Record<string, number>; catalogue: { products: Item[]; categories: Item[] }; audit: { action: string; actor: string; created_at: string }[] };
export type PolicyInput = { branch_uuid: string | null; source: Source; mode: Mode };
export type PolicyPreview = { source: Source; mode: Mode; all_branches: boolean; future_branches: boolean; branches: { uuid: string; name: string; before: Mode; override_removed: boolean; desired_version: number }[]; preview_hash: string };
export type PreviewLine = { line_uuid: string; name: string; name_ar: string | null; product_id: number };
export type RoutingPreview = { work: { area_uuid: string; line: PreviewLine }[]; copies: Record<string, PreviewLine[]>; needs_routing: string[] };
const base = '/api/settings/kitchen';
export const getKitchen = () => apiGet<{ data: Settings }>(base);
export const getKitchenBranch = (id: string) => apiGet<{ data: Detail }>(`${base}/branches/${encodeURIComponent(id)}`);
export const previewPolicy = (input: PolicyInput) => apiPost<{ data: PolicyPreview }>(`${base}/policy-preview`, input);
export const savePolicy = (input: PolicyInput, hash: string) => apiPut<{ data: Settings }>(`${base}/policy`, { ...input, preview_hash: hash });
export const saveRouting = (id: string, bundle: Bundle, version: number) => apiPut<{ data: Detail }>(`${base}/branches/${encodeURIComponent(id)}/routing`, { bundle, expected_version: version });
export const previewRouting = (id: string, bundle: Bundle, version: number, products: number[]) => apiPost<{ data: RoutingPreview }>(`${base}/branches/${encodeURIComponent(id)}/routing-preview`, { bundle, expected_version: version, product_ids: products });
export const activateKitchen = (id: string, version: number, device: string, evidence: string) => apiPost<{ data: Detail }>(`${base}/branches/${encodeURIComponent(id)}/activate`, { expected_version: version, device_uuid: device, isolation_evidence: evidence, confirm_opt_in: true });
